### ISSUE TITLE
`fasterq-dump` image needs an update

### ISSUE THREAD

**Issue by carrascomj** [avsastry/modulome-workflow#13]
It seems like the NCBI APIs are incompatible with the current version of [sratools](https://github.com/ncbi/sra-tools) (I _think_), so the latter must be updated in the [fasterq-dump container](https://hub.docker.com/r/avsastry/fasterq-dump).

Replacing the version number worked for me:

```Dockerfile
FROM ubuntu:18.04

# Metadata
MAINTAINER Anand Sastry <avsastry@ucsd.edu>

# Set noninteractive mode
ENV DEBIAN_FRONTEND noninteractive

# Install pigz and sra-toolbox
USER root
RUN apt-get update && apt-get install -y procps pigz wget libxml-libxml-perl
RUN wget -q http://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/3.0.6/sratoolkit.3.0.6-ubuntu64.tar.gz -O /tmp/sratoolkit.tar.gz && tar zxf /tmp/sratoolkit.tar.gz -C /opt/ && rm /tmp/sratoolkit.tar.gz

RUN mkdir //ncbi && mkdir //ncbi/public && mkdir //ncbi/public/sra && mkdir //ncbi/public/refseq && chmod -R 777 //ncbi

ENV PATH="/opt/sratoolkit.3.0.6-ubuntu64/bin/:${PATH}"
```

**Comment by avsastry** [comment]
Hi @carrascomj, thanks for sending this fix. This repository is now deprecated, but the fixed fasterq-dump image is actively being used at the new home: https://github.com/SBRG/modulome-workflow
