### ISSUE TITLE
Error executing process > 'multiqc (1)'

### ISSUE THREAD

**Issue by bigsuicideparty** [avsastry/modulome-workflow#9]
`nextflow run main.nf -profile local --organism bacillus_subtilis --metadata ../test/test_metadata.tsv --sequence_dir ../test/sequence_files/ --outdir ../test/nf_results/`

Error executing process > 'multiqc (1)'

Caused by:
  Process multiqc (1) terminated with an error exit status (125)

Command executed:

  multiqc -f -c multiqc_config.yaml .
  assemble_qc_stats.py multiqc_data

Command exit status:
  125

Command output:
  (empty)

Command error:
  Unable to find image 'avsastry/multiqc-rockhopper:1.0' locally
  docker: Error response from daemon: pull access denied for avsastry/multiqc-rockhopper, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
  See 'docker run --help'.

Any idea regarding the source of this error?

**Comment by avsastry** [comment]
Fixed in #10
